#!/usr/bin/env bash

UNAMEOUT="$(uname -s)"

# Verify operating system is supported...
case "${UNAMEOUT}" in
    Linux*)             MACHINE=linux;;
    Darwin*)            MACHINE=mac;;
    *)                  MACHINE="UNKNOWN"
esac

if [ "$MACHINE" == "UNKNOWN" ]; then
    echo "Unsupported operating system [$(uname -s)]. Laravel Phalcon supports macOS, Linux, and Windows (WSL2)." >&2

    exit 1
fi

# Determine if stdout is a terminal...
if test -t 1; then
    # Determine if colors are supported...
    ncolors=$(tput colors)

    if test -n "$ncolors" && test "$ncolors" -ge 8; then
        BOLD="$(tput bold)"
        YELLOW="$(tput setaf 3)"
        GREEN="$(tput setaf 2)"
        NC="$(tput sgr0)"
    fi
fi

# Function that prints the available commands...
function display_help {
    echo "Phalcon"
    echo
    echo "${YELLOW}Usage:${NC}" >&2
    echo "  phalcons COMMAND [options] [arguments]"
    echo
    echo "Unknown commands are passed to the docker-compose binary."
    echo
    echo "${YELLOW}docker-compose Commands:${NC}"
    echo "  ${GREEN}phalcons up${NC}        Start the application"
    echo "  ${GREEN}phalcons up -d${NC}     Start the application in the background"
    echo "  ${GREEN}phalcons stop${NC}      Stop the application"
    echo "  ${GREEN}phalcons restart${NC}   Restart the application"
    echo "  ${GREEN}phalcons ps${NC}        Display the status of all containers"
    echo "  ${GREEN}phalcons build --no-cache${NC}       Rebuild all of the Phalcon containers"
    echo
    echo "${YELLOW}Phalcon Commands:${NC}"
    echo "  ${GREEN}phalcons phalcon ...${NC}          Run an Phalcon command"
    echo "  ${GREEN}phalcons phalcon queue:work${NC}"
    echo
    echo "${YELLOW}PHP Commands:${NC}"
    echo "  ${GREEN}phalcons php ...${NC}   Run a snippet of PHP code"
    echo "  ${GREEN}phalcons php -v${NC}"
    echo
    echo "${YELLOW}Composer Commands:${NC}"
    echo "  ${GREEN}phalcons composer ...${NC}                       Run a Composer command"
    echo "  ${GREEN}phalcons composer require laravel/sanctum${NC}"
    echo
    echo
    echo "${YELLOW}NPM Commands:${NC}"
    echo "  ${GREEN}phalcons npm ...${NC}        Run a npm command"
    echo "  ${GREEN}phalcons npm run prod${NC}"
    echo
    echo
    echo "${YELLOW}Database Commands:${NC}"
    echo "  ${GREEN}phalcons mysql${NC}             Start a MySQL CLI session within the 'mysql' container"
    echo "  ${GREEN}phalcons migrate${NC}           Run database migrations"
    echo "  ${GREEN}phalcons migrate:generate${NC}  Generate database migrations"
    echo "  ${GREEN}phalcons migrate:list${NC}      List all migrations"
    echo
    echo "${YELLOW}Debugging:${NC}"
    echo "  ${GREEN}phalcons debug ...${NC}          Run an Phalcon command in debug mode"
    echo "  ${GREEN}phalcons debug queue:work${NC}"
    echo
    echo "${YELLOW}Running Tests:${NC}"
    echo "  ${GREEN}phalcons test${NC}          Run the PHPUnit tests via the Phalcon test command"
    echo
    echo "${YELLOW}Container CLI:${NC}"
    echo "  ${GREEN}phalcons shell${NC}        Start a shell session within the application container"
    echo "  ${GREEN}phalcons bash${NC}         Alias for 'phalcons shell'"
    echo "  ${GREEN}phalcons root-shell${NC}   Start a root shell session within the application container"
    echo "  ${GREEN}phalcons root-bash${NC}    Alias for 'phalcons root-shell'"
    echo "  ${GREEN}phalcons tinker${NC}       Start a new Laravel Tinker session"
    echo
    echo "${YELLOW}Sharing:${NC}"
    echo "  ${GREEN}phalcons share${NC}   Share the application publicly via a temporary URL"
    echo
    echo "${YELLOW}Binaries:${NC}"
    echo "  ${GREEN}phalcons bin ...${NC}   Run Composer binary scripts from the vendor/bin directory"
    echo
    exit 1
}

# Proxy the "help" command...
if [ $# -gt 0 ]; then
    if [ "$1" == "help" ] || [ "$1" == "-h" ] || [ "$1" == "-help" ] || [ "$1" == "--help" ]; then
        display_help
    fi
else
    display_help
fi

# Source the ".env" file so Laravel's environment variables are available...
if [ ! -z "$APP_ENV" ] && [ -f ./.env.$APP_ENV ]; then
  source ./.env.$APP_ENV;
elif [ -f ./.env ]; then
  source ./.env;
fi

# Define environment variables...
export APP_PORT=${APP_PORT:-80}
export APP_SERVICE=${APP_SERVICE:-"laravel.test"}
export DB_PORT=${DB_PORT:-3306}
export WWWUSER=${WWWUSER:-$UID}
export WWWGROUP=${WWWGROUP:-$(id -g)}

export SAIL_FILES=${SAIL_FILES:-""}
export SAIL_SHARE_DASHBOARD=${SAIL_SHARE_DASHBOARD:-4040}
export SAIL_SHARE_SERVER_HOST=${SAIL_SHARE_SERVER_HOST:-"laravel-phalcons.site"}
export SAIL_SHARE_SERVER_PORT=${SAIL_SHARE_SERVER_PORT:-8080}
export SAIL_SHARE_SUBDOMAIN=${SAIL_SHARE_SUBDOMAIN:-""}
export SAIL_SHARE_DOMAIN=${SAIL_SHARE_DOMAIN:-""}

# Function that outputs Phalcon is not running...
function phalcons_is_not_running {
    echo "${BOLD}Phalcon is not running.${NC}" >&2
    echo "" >&2
    echo "${BOLD}You may Phalcon using the following commands:${NC} './vendor/bin/phalcons up' or './vendor/bin/phalcons up -d'" >&2

    exit 1
}

# Define Docker Compose command prefix...
docker compose &> /dev/null
if [ $? == 0 ]; then
    DOCKER_COMPOSE=(docker compose)
else
    DOCKER_COMPOSE=(docker-compose)
fi

if [ -n "$SAIL_FILES" ]; then
    # Convert SAIL_FILES to an array...
    IFS=':' read -ra SAIL_FILES <<< "$SAIL_FILES"

    for FILE in "${SAIL_FILES[@]}"; do
        if [ -f "$FILE" ]; then
            DOCKER_COMPOSE+=(-f "$FILE")
        else
            echo "${BOLD}Unable to find Docker Compose file: '${FILE}'${NC}" >&2

            exit 1
        fi
    done
fi

EXEC="yes"

if [ -z "$SAIL_SKIP_CHECKS" ]; then
    # Ensure that Docker is running...
    if ! docker info > /dev/null 2>&1; then
        echo "${BOLD}Docker is not running.${NC}" >&2

        exit 1
    fi

    # Determine if Phalcon is currently up...
    if "${DOCKER_COMPOSE[@]}" ps "$APP_SERVICE" 2>&1 | grep 'Exit\|exited'; then
        echo "${BOLD}Shutting down old Phalcon processes...${NC}" >&2

        "${DOCKER_COMPOSE[@]}" down > /dev/null 2>&1

        EXEC="no"
    elif [ -z "$("${DOCKER_COMPOSE[@]}" ps -q)" ]; then
        EXEC="no"
    fi
fi

ARGS=()

# Proxy PHP commands to the "php" binary on the application container...
if [ "$1" == "php" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" "php" "$@")
    else
        phalcons_is_not_running
    fi

# Proxy vendor binary commands on the application container...
elif [ "$1" == "bin" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" ./vendor/bin/"$@")
    else
        phalcons_is_not_running
    fi

# Proxy docker-compose commands to the docker-compose binary on the application container...
elif [ "$1" == "docker-compose" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" "${DOCKER_COMPOSE[@]}")
    else
        phalcons_is_not_running
    fi

# Proxy Composer commands to the "composer" binary on the application container...
elif [ "$1" == "composer" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" "composer" "$@")
    else
        phalcons_is_not_running
    fi

# Proxy Phalcon commands to the "phalcon" binary on the application container...
elif [ "$1" == "phalcon" ] || [ "$1" == "art" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" phalcon "$@")
    else
        phalcons_is_not_running
    fi

# Proxy the "debug" command to the "php phalcon" binary on the application container with xdebug enabled...
elif [ "$1" == "debug" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons -e XDEBUG_SESSION=1)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" phalcon "$@")
    else
        phalcons_is_not_running
    fi

# Proxy the "test" command to the "phalcon test" Phalcon command...
elif [ "$1" == "test" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" phalcon test "$@")
    else
        phalcons_is_not_running
    fi

# Initiate a Laravel Tinker session within the application container...
elif [ "$1" == "tinker" ] ; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" phalcon tinker)
    else
        phalcons_is_not_running
    fi

# Proxy Node commands to the "node" binary on the application container...
elif [ "$1" == "node" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" node "$@")
    else
        phalcons_is_not_running
    fi

# Proxy NPM commands to the "npm" binary on the application container...
elif [ "$1" == "npm" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" npm "$@")
    else
        phalcons_is_not_running
    fi

# Proxy NPX commands to the "npx" binary on the application container...
elif [ "$1" == "npx" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" npx "$@")
    else
        phalcons_is_not_running
    fi


# Initiate a MySQL CLI terminal session within the "mysql" container...
elif [ "$1" == "mysql" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=(mysql bash -c)
        ARGS+=("MYSQL_PWD=\${MYSQL_PASSWORD} mysql -u \${MYSQL_USER} \${MYSQL_DATABASE}")
    else
        phalcons_is_not_running
    fi


# Initiate a Bash shell within the application container...
elif [ "$1" == "shell" ] || [ "$1" == "bash" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" bash "$@")
    else
        phalcons_is_not_running
    fi

# Initiate a root user Bash shell within the application container...
elif [ "$1" == "root-shell" ] || [ "$1" == "root-bash" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" bash "$@")
    else
        phalcons_is_not_running
    fi

# Initiate a Redis CLI terminal session within the "redis" container...
elif [ "$1" == "redis" ] ; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=(redis redis-cli)
    else
        phalcons_is_not_running
    fi
# Proxy migration commands to phalcon-migrations
elif [ "$1" == "migrate" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" ./vendor/bin/phalcon-migrations run --config=migrations.php)
    else
        phalcons_is_not_running
    fi

# Generate migrations
elif [ "$1" == "migrate:generate" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        if [ $# -gt 0 ]; then
            # If there are additional arguments, pass them through
            ARGS+=("$APP_SERVICE" ./vendor/bin/phalcon-migrations generate --config=migrations.php "$@")
        else
            # If no additional arguments, run basic generate
            ARGS+=("$APP_SERVICE" ./vendor/bin/phalcon-migrations generate --config=migrations.php)
        fi
    else
        phalcons_is_not_running
    fi

# List migrations
elif [ "$1" == "migrate:list" ]; then
    shift 1

    if [ "$EXEC" == "yes" ]; then
        ARGS+=(exec -u phalcons)
        [ ! -t 0 ] && ARGS+=(-T)
        ARGS+=("$APP_SERVICE" ./vendor/bin/phalcon-migrations list --config=migrations.php)
    else
        phalcons_is_not_running
    fi

# Pass unknown commands to the "docker-compose" binary...
else
    ARGS+=("$@")
fi

# Run Docker Compose with the defined arguments...
"${DOCKER_COMPOSE[@]}" "${ARGS[@]}"
