<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Phalcon PHP Framework</title>
  <script src="//unpkg.com/mithril/mithril.js"></script>
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/octicons/3.5.0/octicons.min.css">
  <link rel="stylesheet" href="/css/ImaLab.css">
</head>
<body>

<div id="main" class="container-fluid">
  <div id="main" class="container-fluid main ">
    <div id="grid" class="row">
      <div class="col-sm-3">
        <div>
          <h1>Projects</h1>
          <div class="form">
            <form method="post">

            </form>
          </div>
        </div>
        <div id="projects" >

        </div>
      </div>
      <div class="col-sm-3">
        <div>
          <h1>Posts</h1>
        </div>
        <div id="posts" >

        </div>
      </div>
      <div class="col-sm-3">
        <div>
          <h1>Packages</h1>
        </div>
        <div id="packages" >
        </div>
      </div>
        <div class="col-sm-3">
        <div>
          <h1>Users</h1>
        </div>
        <div id="packages" >
        </div>
      </div>
    </div>
  </div>
</div>
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.min.js"></script>

</body>
<script src="/js/App.js"></script>

</html>
