<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Phalcon PHP Framework</title>
    <script src="//unpkg.com/mithril/mithril.js"></script>
    <link rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/octicons/3.5.0/octicons.min.css">

    <script
            src="//cdnjs.cloudflare.com/ajax/libs/filepond/4.30.4/filepond.min.js"></script>
    <link rel="stylesheet" href="<?php echo $this->url->get('css/Admin.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->url->get('https://cdnjs.cloudflare.com/ajax/libs/filepond/4.30.4/filepond.css'); ?>">
</head>
<body>

<div id="main"></div>

</body>
<script src="<?php echo $this->url->get('js/Admin.js'); ?>"></script>
</html>