<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>The I am Labs Project Showcace</title>
  <link rel="stylesheet" href="/css/bootstrap.css">
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/octicons/3.5.0/octicons.min.css">
  <link rel="stylesheet" href="/css/ImaLab.css">

</head>
<body>
<nav class="nav sidebar" role="navigation">
  <div class="container-fluid">
    <div class="brand">
      <img
        class="img-fluid"
        src="/img/logo.png"
        alt="Iam Labs"
      >
    </div>
    <div id="navCollapse">
      <ul class="inner">
        <li class="item">
          <a class="link" href="/">Home
            <i class="pull-right octicon octicon-home"></i>
          </a>
        </li>
        <li class="item">
          <a class="link" href="/projects">Projects
            <i class="octicon octicon-beaker"></i>
          </a>
        </li>
        <li class="item">
          <a class="link" href="/packages">Packages
            <i class="octicon octicon-mark-github"></i>
          </a>
        </li>
        <li class="item">
          <a class="link" href="/about">About
            <i class="octicon octicon-broadcast"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div id="main" class="container-fluid main login">

    <div class="row vertical-offset-100">
      <div class="col-sm-4 "> </div>
      <div class="col-sm-4 ">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Please sign in</h3>
          </div>
          <div class="panel-body">
            <form accept-charset="UTF-8" role="form" method="post">
              <fieldset>
                <div class="form-group">
                  <input class="form-control" placeholder="E-mail" name="email" type="text">
                </div>
                <div class="form-group">
                  <input class="form-control" placeholder="Password" name="password" type="password" value="">
                </div>
                <div class="checkbox">
                  <label>
                    <input name="remember" type="checkbox" value="Remember Me"> Remember Me
                  </label>
                </div>
                <input class="btn btn-lg btn-success btn-block" type="submit" value="Login">
              </fieldset>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
