<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>The I am Labs Project Showcace</title>
    <script src="//unpkg.com/mithril/mithril.js"></script>
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/octicons/3.5.0/octicons.min.css">
  <link rel="stylesheet" href="/css/ImaLab.css">

</head>
<body>
<nav id="menu" class="nav sidebar" role="navigation">
  <div class="container-fluid">
    <div class="brand">
      <img
        class="img-fluid"
        src="/img/IAMLablogo-export.png"
        alt="Iam Labs"
      >
        <div class="sr-only"> I am <span class="link-text">Lab</span></div>
    </div>
    <div id="navCollapse">
      <ul class="inner">
        <li class="item">
          <a class="link" href="/">
              <span class="link-text">Home</span>
            <i class="pull-right octicon octicon-home"></i>
          </a>
        </li>
        <li class="item">
          <a class="link" href="/#!/projects">
              <span class="link-text">Projects</span>
            <i class="octicon octicon-beaker"></i>
          </a>
        </li>
        <li class="item">
          <a class="link" href="/#!/packages">
              <span class="link-text">Packages</span>
            <i class="octicon octicon-mark-github"></i>
          </a>
        </li>
        <li class="item">
          <a class="link" href="/#!/code">
              <span class="link-text">Code</span>
            <i class="octicon octicon-code"></i>
          </a>
        </li>
          <li class="item">
          <a class="link" href="/#!/about">
              <span class="link-text">About</span>
            <i class="octicon octicon-broadcast"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div id="main" class="container-fluid main ">


</div>




</body>
<script src="/js/App.js"></script>
</html>
