<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>The I am Labs Project Showcace</title>
    <script src="//unpkg.com/mithril/mithril.js"></script>
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/octicons/3.5.0/octicons.min.css">
  <link rel="stylesheet" href="/css/ImaLab.css">

</head>
<body>
<div id="app">

</div>



</body>
<script src="/js/App.js"></script>
</html>
