brend:
  config:
    enviroment: dev
    port: 8090
    autoprefix:
      browsers: last 2 versions
  javascript:
    src:
      - './assets/components/jquery/dist/jquery.js'
      - './assets/components/imagesloaded/imagesloaded.pkgd.js'
      - './assets/components/masonry/dist/masonry.pkgd.js'
      - './assets/components/markdown/lib/markdown.js'
      - './assets/js/Project/ProjectModule.js'
      - './assets/js/Post/PostsModule.js'
      - './assets/js/Package/PackageModule.js'
      - './assets/js/All/AllModule.js'
      - './assets/js/About/AboutModule.js'
      - './assets/js/App.js'
      - './assets/js/ImaLab.js'
    dist: './public/js/'
    output: 'scripts.js'
  scss:
    src:
      - './assets/components/bootstrap/scss/bootstrap.scss'
      - './assets/scss/**/*.scss'
    dist: './public/css/'
    output: 'style.css'
  img:
    src:
     - './assets/img/**/*.{png|jpg|gif|svg}'
    dist: './public/img/'
  watch:
    scss:
      - './assets/scss/**/*.scss'
    js:
      - './assets/js/**/*.js'
    img:
      - './assets/img/**/*.{png|jpg|gif|svg}'